*&---------------------------------------------------------------------*
*& Module Pool      ZGC_MPP_POCDM_1
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
PROGRAM ZGC_MPP_POCDM_1.

DATA: lt_header TYPE TABLE OF ZGC_1_OH,
      ls_header TYPE ZGC_1_OH.

DATA: lt_item TYPE TABLE OF ZGC_1_OI,
      ls_item TYPE ZGC_1_OI.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TBL_ITEMS' ITSELF
CONTROLS: TBL_ITEMS TYPE TABLEVIEW USING SCREEN 0141.

*&SPWIZARD: OUTPUT MODULE FOR TC 'TBL_ITEMS'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: UPDATE LINES FOR EQUIVALENT SCROLLBAR
MODULE TBL_ITEMS_CHANGE_TC_ATTR OUTPUT.
  DESCRIBE TABLE LT_ITEM LINES TBL_ITEMS-lines.
ENDMODULE.

*&SPWIZARD: INPUT MODULE FOR TC 'TBL_ITEMS'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: MODIFY TABLE
MODULE TBL_ITEMS_MODIFY INPUT.
  MODIFY LT_ITEM
    FROM LS_ITEM
    INDEX TBL_ITEMS-CURRENT_LINE.
ENDMODULE.

INCLUDE zgc_mpp_pocdm_1_f4_recommeni01.

INCLUDE zgc_mpp_pocdm_1_f4_recommeni02.
